// From Celeste
const MAX_RUN_SPEED = 90;
const RUN_ACCELERATION = 1000;
const RUN_DECELERATION = 400;
const AIR_FACTOR = .65;
const JUMP_SPEED = 105;
const JUMP_HORIZONTAL_BOOST = 40;
const MAX_FALL_SPEED = 160;
const GRAVITY = 900;
const JUMP_GRACE_TIME = .1;
const VAR_JUMP_TIME = .2;
const CLIMB_SLIP_SPEED = 30;
const WALL_JUMP_CHECK_DISTANCE = 3;
const WALL_JUMP_HSPEED = MAX_RUN_SPEED + JUMP_HORIZONTAL_BOOST;
const WALL_JUMP_FORCE_TIME = .16;

const SLOWDOWN_FACTOR = 1;

const FRAMES_PER_SECOND = 60;

const WIDTH = 320;
const HEIGHT = 200;
const SCALING = 2;
const GRID_SIZE = 8;
const START_POSITION_X = 2;
const START_POSITION_Y = 6;